### PR TITLE
test: add obj_alloc_mt test

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 5 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp4_RHBRM3ecq8khkB:-NSp4_RHBRM3ecq8khkC:undefined) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L5)):*
> ```C
> 
> /*
>  * obj_palloc_mt.c -- multithreaded test of allocator
> ```





_Suggestion:_
```C
_alloc
```
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 19 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp3Q7qB1DjNjllvfEQ:-NSp3Q7qB1DjNjllvfER:bvis7l0) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L19)):*
> ```C
> #define ALLOC_SIZE 104
> #define REALLOC_SIZE (ALLOC_SIZE * 3)
> #define MIX_RERUNS 2
> ```

Let's increase the probability of conflict between tests.



_Suggestion:_
```C
#define MIX_RERUNS 10
```
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 54 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp08Iz9ZFh4zrNX-9E:-NSp08Iz9ZFh4zrNX-9F:bjxq5lq) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L54)):*
> ```C
> 		int err = pmemobj_alloc(a->pop, &a->oid, ALLOC_SIZE,
> 			0, NULL, NULL);
> 		UT_ASSERTeq(err, 0);
> ```

We should also validate oid with ``UT_ASSERT(!OID_IS_NULL(oid));``



_Code quote:_
```C
		UT_ASSERTeq(err, 0);
```
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 55 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp0NDjELUWrVSOqohf:-NSp0NDjELUWrVSOqohg:b-5boxr2) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L55)):*
> ```C
> 			0, NULL, NULL);
> 		UT_ASSERTeq(err, 0);
> 		pmemobj_free(&a->oid);
> ```

Free shall be called in ``free_worker()`` only.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 68 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp1XmBAKF8rz-1DT5z:-NSp1XmBAKF8rz-1DT6-:bjxq5lq) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L68)):*
> ```C
> 	for (unsigned i = 0; i < Ops_per_thread; ++i) {
> 		int err = pmemobj_realloc(a->pop, &a->oid, REALLOC_SIZE, 0);
> 		UT_ASSERTeq(err, 0);
> ```

We should also validate oid with ``UT_ASSERT(!OID_IS_NULL(oid));``



_Code quote:_
```C
UT_ASSERTeq(err, 0);
```
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 100 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp1raz8ZmU7RzU1PE-:-NSp1raz8ZmU7RzU1PE0:bjxq5lq) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L100)):*
> ```C
> 			int err = pmemobj_alloc(a->pop, &a->oid, ALLOC_SIZE,
> 				0, NULL, NULL);
> 			UT_ASSERTeq(err, 0);
> ```

We should also validate oid with ``UT_ASSERT(!OID_IS_NULL(oid));``



_Code quote:_
```C
			UT_ASSERTeq(err, 0);
```
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 127 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp2gqCCQHIUa-4bqhi:-NSp2gqCCQHIUa-4bqhj:bka6z21) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L127)):*
> ```C
> }
> 
> static void *
> ```

Does obj_pnmalloc_mt already cover it?



_Code quote:_
```C
static void *
action_cancel_worker(void *arg)
{
	struct worker_args *a = arg;

	PMEMoid oid;
	for (unsigned i = 0; i < Ops_per_thread; ++i) {
		unsigned arr_id = a->idx / 2;
		struct action *act = &a->r->actions[arr_id][i];
		if (a->idx % 2 == 0) {
			os_mutex_lock(&act->lock);
			oid = pmemobj_reserve(a->pop,
				&act->pact, ALLOC_SIZE, 0);
			UT_ASSERT(!OID_IS_NULL(oid));
			os_cond_signal(&act->cond);
			os_mutex_unlock(&act->lock);
		} else {
			os_mutex_lock(&act->lock);
			while (act->pact.heap.offset == 0)
				os_cond_wait(&act->cond, &act->lock);
			pmemobj_cancel(a->pop, &act->pact, 1);
			os_mutex_unlock(&act->lock);
		}
	}

	return NULL;
}

static void *
action_publish_worker(void *arg)
{
	struct worker_args *a = arg;

	PMEMoid oid;
	for (unsigned i = 0; i < Ops_per_thread; ++i) {
		unsigned arr_id = a->idx / 2;
		struct action *act = &a->r->actions[arr_id][i];
		if (a->idx % 2 == 0) {
			os_mutex_lock(&act->lock);
			oid = pmemobj_reserve(a->pop,
				&act->pact, ALLOC_SIZE, 0);
			UT_ASSERT(!OID_IS_NULL(oid));
			os_cond_signal(&act->cond);
			os_mutex_unlock(&act->lock);
		} else {
			os_mutex_lock(&act->lock);
			while (act->pact.heap.offset == 0)
				os_cond_wait(&act->cond, &act->lock);
			pmemobj_publish(a->pop, &act->pact, 1);
			os_mutex_unlock(&act->lock);
		}
	}

	return NULL;
}

static void *
action_mix_worker(void *arg)
{
	struct worker_args *a = arg;

	PMEMoid oid;
	for (unsigned i = 0; i < Ops_per_thread; ++i) {
		unsigned arr_id = a->idx / 2;
		unsigned publish = i % 2;
		struct action *act = &a->r->actions[arr_id][i];
		if (a->idx % 2 == 0) {
			os_mutex_lock(&act->lock);
			oid = pmemobj_reserve(a->pop,
				&act->pact, ALLOC_SIZE, 0);
			UT_ASSERT(!OID_IS_NULL(oid));
			os_cond_signal(&act->cond);
			os_mutex_unlock(&act->lock);
		} else {
			os_mutex_lock(&act->lock);
			while (act->pact.heap.offset == 0)
				os_cond_wait(&act->cond, &act->lock);
			if (publish)
				pmemobj_publish(a->pop, &act->pact, 1);
			else
				pmemobj_cancel(a->pop, &act->pact, 1);
			os_mutex_unlock(&act->lock);
		}
		pmemobj_persist(a->pop, act, sizeof(*act));
	}

	return NULL;
}

static void
actions_clear(PMEMobjpool *pop, struct root *r)
{
	for (unsigned i = 0; i < Threads; ++i) {
		for (unsigned j = 0; j < Ops_per_thread; ++j) {
			struct action *a = &r->actions[i][j];
			util_mutex_destroy(&a->lock);
			util_mutex_init(&a->lock);
			util_cond_destroy(&a->cond);
			util_cond_init(&a->cond);
			memset(&a->pact, 0, sizeof(a->pact));
			pmemobj_persist(pop, a, sizeof(*a));
		}
	}
}
```
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 298 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp2DoM9CYh672dW1w2:-NSp2DoM9CYh672dW1w3:b-l5us7y) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L298)):*
> ```C
> 
> 	run_worker(alloc_worker, args);
> 	run_worker(realloc_worker, args);
> ```

Let's try to build the following logic (use cases)
alloc + free
alloc + realloc + free
mix_worker
alloc_free_worker



_Code quote:_
```C
	run_worker(alloc_worker, args);
	run_worker(realloc_worker, args);
	run_worker(free_worker, args);
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: all files reviewed, 16 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 127 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp2gqCCQHIUa-4bqhi:-NSpxsY06ZsJWtMcGev9:bj8wkdu) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes. It does. I recommend keeping the above here and removing it from the obj_pmalloc_mt, as the latter is a more internal kind of test.
</blockquote></details>

But would it be better to move reserve/publish tests to a separate folder?

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 5 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp4_RHBRM3ecq8khkB:-NStW8TN8giuRU_dd9mz:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L5)):*
> ```C
> 
> /*
>  * obj_palloc_mt.c -- multithreaded test of allocator
> ```

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 5 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSpR5Yj5jsYzdKQC7tB:-NStWAYj5Eqi-kqFp-Id:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**the** allocator
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 10 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSpVKq343usi9zTIUzN:-NStWZ4B2McITFSlLHss:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we use the public libpmemobj.h header file instead of the internal one?
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 11 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSpW4rO-8VWXTEG4AN2:-NStWZl5Epq6QpAridmW:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 19 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp3Q7qB1DjNjllvfEQ:-NStz__53ZFZkLnCM-M5:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Let's increase the probability of conflict between tests.
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 54 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp08Iz9ZFh4zrNX-9E:-NStXvj_EDtY334Q9u0A:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L54)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We should also validate oid with ``UT_ASSERT(!OID_IS_NULL(oid));``
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 55 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp0NDjELUWrVSOqohf:-NStY8pc3ZRjptd-RbJq:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L55)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Free shall be called in ``free_worker()`` only.
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 68 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp1XmBAKF8rz-1DT5z:-NStYHN40o7TdX4ljFRo:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L68)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We should also validate oid with ``UT_ASSERT(!OID_IS_NULL(oid));``
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 81 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSplOHq1IxIf_Y9rwoM:-NSt_CLH3wpCaGfVCqVx:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> oidp is set to OID_NULL after the memory is freed.

So, I guess we can test e.g.

```c
UT_ASSERT(OID_IS_NULL(oid));
```
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 100 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp1raz8ZmU7RzU1PE-:-NSt_Rze0NpupdN_APLA:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L100)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We should also validate oid with ``UT_ASSERT(!OID_IS_NULL(oid));``
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 104 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSpmR3X9dCp9otCG5nr:-NSt_TRdBDeKORdH8TF5:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L104)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 118 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSpmXUN9uNnWnc-6IRq:-NSta5D23mZXbHsuCF2q:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L118)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 121 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSpmY7j4bRIgYWMGj5r:-NSta6An0bg7Wpogq4YW:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L121)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 127 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp2gqCCQHIUa-4bqhi:-NStaYfAAJnd_NYoRxMQ:b-eg4a0s) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L127)):*
> But would it be better to move reserve/publish tests to a separate folder?
I propose to make a separate PR
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 298 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSp2DoM9CYh672dW1w2:-NStblJU0eEIR9oBkfMQ:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/obj_alloc_mt.c#L298)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Let's try to build the following logic (use cases)
alloc + free
alloc + realloc + free
mix_worker
alloc_free_worker
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/TEST3` line 14 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSpSJ983AOuxgwLHDKg:-NStc36p6HE0N4uuyPls:bl3hx9) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/TEST3#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is the difference compared to the obj_pmalloc_mt/TEST3 intentional?
</blockquote></details>

This test takes about 7 seconds in both cases

**Review by janekmi — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 53 at r2](https://reviewable.io/reviews/osalyk/pmdk/7#-NSulccHBxbv5MmbCuIu:-NSulccHBxbv5MmbCuIv:b-tqzced) ([raw file](https://github.com/osalyk/pmdk/blob/9bfa79d78a2ee467f516e81e19126ba659ca3a79/src/test/obj_alloc_mt/obj_alloc_mt.c#L53)):*
> ```C
> 			0, NULL, NULL);
> 		UT_ASSERT(!OID_IS_NULL(a->oid[a->idx][i]));
> 		UT_ASSERTeq(err, 0);
> ```

I think the opposite order of checks would be better.
1. It is more logical. The oid value is irrelevant when the allocation has failed.
2. It will allow discrimination between two failed scenarios at the first glance:
a) either pmemobj_alloc(3) has failed or
b) pmemobj_alloc(3) has not failed (err == 0) but oid is still NULL.



_Code quote:_
```C
		UT_ASSERT(!OID_IS_NULL(a->oid[a->idx][i]));
		UT_ASSERTeq(err, 0);
```
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 53 at r2](https://reviewable.io/reviews/osalyk/pmdk/7#-NSumOLr2VGw0BKUt2bH:-NSumOLr2VGw0BKUt2bI:bg33u0n) ([raw file](https://github.com/osalyk/pmdk/blob/9bfa79d78a2ee467f516e81e19126ba659ca3a79/src/test/obj_alloc_mt/obj_alloc_mt.c#L53)):*
> ```C
> 			0, NULL, NULL);
> 		UT_ASSERT(!OID_IS_NULL(a->oid[a->idx][i]));
> 		UT_ASSERTeq(err, 0);
> ```

The b) scenario from the comment above allowed me to realize that if we would not "zero" the oid array before calling pmemobj_alloc(3) the type-b fail would remain hidden till someone will try to use the invalid (not-set) oid. We would be lucky if it will fail immediately. Because the old value might be as well identified as valid and processed which would further hide the issue.

The fail scenario I think about:

```c
oid = some_invalid_value;
assert pmemobj_alloc(&oid) == 0 // failed silently (type-b fail)
assert oid == some_invalid_value // so, the oid remained the same
...
pmemobj_free(oid) // may fail, may succeed, drawing us away from the culprit
```

whereas with zeroed oid:
```c
oid = OID_NULL
assert pmemobj_alloc(&oid) == 0 // failed silently (type-b fail)
assert oid == OID_NULL // so, the oid remained zeroed which we can easily detect and stop
```
___
*[`src/test/obj_alloc_mt/TEST3` line 14 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSpSJ983AOuxgwLHDKg:-NSuskUU15B0sN40cHNd:b-gkjm6v) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/TEST3#L14)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This test takes about 7 seconds in both cases
</blockquote></details>

Short? :laughing:

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 39 at r2](https://reviewable.io/reviews/osalyk/pmdk/7#-NSuutih53VYmDej9RAw:-NSuutih53VYmDej9RAx:b-mg63ds) ([raw file](https://github.com/osalyk/pmdk/blob/9bfa79d78a2ee467f516e81e19126ba659ca3a79/src/test/obj_alloc_mt/obj_alloc_mt.c#L39)):*
> ```C
> struct worker_args {
> 	PMEMobjpool *pop;
> 	PMEMoid oid[MAX_THREADS][MAX_OPS_PER_THREAD];
> ```

`struct worker_args` are already multiplied by MAX_THREADS here:

```c
struct worker_args args[MAX_THREADS];
```
 
By moving the oids outside of the root you made a separate array for each of the threads.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 39 at r2](https://reviewable.io/reviews/osalyk/pmdk/7#-NSuvJn59iACtI3hV_2k:-NSuvJn59iACtI3hV_2l:b3k884x) ([raw file](https://github.com/osalyk/pmdk/blob/9bfa79d78a2ee467f516e81e19126ba659ca3a79/src/test/obj_alloc_mt/obj_alloc_mt.c#L39)):*
> ```C
> struct worker_args {
> 	PMEMobjpool *pop;
> 	PMEMoid oid[MAX_THREADS][MAX_OPS_PER_THREAD];
> ```

oid -> oids I guess.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: 7 of 8 files reviewed, 12 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 39 at r2](https://reviewable.io/reviews/osalyk/pmdk/7#-NSuutih53VYmDej9RAw:-NSyS50Q8GqZfV7OMjA7:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/9bfa79d78a2ee467f516e81e19126ba659ca3a79/src/test/obj_alloc_mt/obj_alloc_mt.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`struct worker_args` are already multiplied by MAX_THREADS here:

```c
struct worker_args args[MAX_THREADS];
```
 
By moving the oids outside of the root you made a separate array for each of the threads.
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 39 at r2](https://reviewable.io/reviews/osalyk/pmdk/7#-NSuvJn59iACtI3hV_2k:-NSyS5sG3ntXlt_87bOk:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/9bfa79d78a2ee467f516e81e19126ba659ca3a79/src/test/obj_alloc_mt/obj_alloc_mt.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

oid -> oids I guess.
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 53 at r2](https://reviewable.io/reviews/osalyk/pmdk/7#-NSulccHBxbv5MmbCuIu:-NSyStiV4mY2hIfJ4PeS:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/9bfa79d78a2ee467f516e81e19126ba659ca3a79/src/test/obj_alloc_mt/obj_alloc_mt.c#L53)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the opposite order of checks would be better.
1. It is more logical. The oid value is irrelevant when the allocation has failed.
2. It will allow discrimination between two failed scenarios at the first glance:
a) either pmemobj_alloc(3) has failed or
b) pmemobj_alloc(3) has not failed (err == 0) but oid is still NULL.
</blockquote></details>

Done.
___
*[`src/test/obj_alloc_mt/TEST3` line 14 at r1](https://reviewable.io/reviews/osalyk/pmdk/7#-NSpSJ983AOuxgwLHDKg:-NSyToSVCKbi6y7ngJfT:br1j4mu) ([raw file](https://github.com/osalyk/pmdk/blob/c0026081586e12de5c472c87516691704db2f440/src/test/obj_alloc_mt/TEST3#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Short? :laughing: 
</blockquote></details>

After all the changes, it lasts 23,721 s. I think the medium will be fine.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[`src/test/obj_alloc_mt/obj_alloc_mt.c` line 53 at r2](https://reviewable.io/reviews/osalyk/pmdk/7#-NSumOLr2VGw0BKUt2bH:-NSyfo0TAKJmhuEgwnQ_:b-896fix) ([raw file](https://github.com/osalyk/pmdk/blob/9bfa79d78a2ee467f516e81e19126ba659ca3a79/src/test/obj_alloc_mt/obj_alloc_mt.c#L53)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The b) scenario from the comment above allowed me to realize that if we would not "zero" the oid array before calling pmemobj_alloc(3) the type-b fail would remain hidden till someone will try to use the invalid (not-set) oid. We would be lucky if it will fail immediately. Because the old value might be as well identified as valid and processed which would further hide the issue.

The fail scenario I think about:

```c
oid = some_invalid_value;
assert pmemobj_alloc(&oid) == 0 // failed silently (type-b fail)
assert oid == some_invalid_value // so, the oid remained the same
...
pmemobj_free(oid) // may fail, may succeed, drawing us away from the culprit
```

whereas with zeroed oid:
```c
oid = OID_NULL
assert pmemobj_alloc(&oid) == 0 // failed silently (type-b fail)
assert oid == OID_NULL // so, the oid remained zeroed which we can easily detect and stop
```
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7#-:-NSz6KoG-52mSMAtINW5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/7#-:-NTD4k6tDuAmRqnFN7FW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
