### PR TITLE
common: synchronize master branch with pmem/master

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/osalyk/pmdk/10)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/10)* status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)

___
*[`utils/docker/packages/test-packages-installation.py` line 68 at r6](https://reviewable.io/reviews/osalyk/pmdk/10#-NTmRZj-7mBOS0XKpzRh:-NTmmVNpE1nUhxa_4Zjf:b-fh1r6g) ([raw file](https://github.com/osalyk/pmdk/blob/c6161fbb596de766b11ebdf62fbd570152a9d28a/utils/docker/packages/test-packages-installation.py#L68)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

This is a workaround for a specific opensuse related issue. When you make rpm packages, some (not all of them) package names have a number '1' added to them. This would cause test failures since these packages would be either ignored by the script or break it.
The code just replaces the numbers with nothing, so they can be treated like the rest of normal packages.
</blockquote></details>

Should we be worried that this code:

- is run regardless of the distribution?
- does not differentiate between the "1" added by OpenSUSE vs the "1" is there on purpose?
- makes version "2.2.1" and "2.2.11" look exactly the same?

**Review by tszczyp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/10)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[`utils/docker/packages/test-packages-installation.py` line 68 at r6](https://reviewable.io/reviews/osalyk/pmdk/10#-NTmRZj-7mBOS0XKpzRh:-NTmsOiw8glJyXvo_pcn:btts899) ([raw file](https://github.com/osalyk/pmdk/blob/c6161fbb596de766b11ebdf62fbd570152a9d28a/utils/docker/packages/test-packages-installation.py#L68)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Should we be worried that this code:

- is run regardless of the distribution?
- does not differentiate between the "1" added by OpenSUSE vs the "1" is there on purpose?
- makes version "2.2.1" and "2.2.11" look exactly the same?
</blockquote></details>

- The "1" is added only in OpenSUSE, having no effect on other distributions, so OS restriction wasn't needed, the code is simply ignored.
- The change does not influence the 'version' part of the package name, only its prefix:
libpmem21-1.12.1+(...).rpm
libpmem21-debuginfo-1.12.1+(...).rpm
into:
libpmem2-1.12.1+(...).rpm
libpmem2-debuginfo-1.12.1+(...).rpm
which keeps the package names consistent
( example of package names before the change )

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[`utils/docker/packages/test-packages-installation.py` line 68 at r6](https://reviewable.io/reviews/osalyk/pmdk/10#-NTmRZj-7mBOS0XKpzRh:-NTnbTKz7JE-gCngTwZ2:bijvphd) ([raw file](https://github.com/osalyk/pmdk/blob/c6161fbb596de766b11ebdf62fbd570152a9d28a/utils/docker/packages/test-packages-installation.py#L68)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

- The "1" is added only in OpenSUSE, having no effect on other distributions, so OS restriction wasn't needed, the code is simply ignored.
- The change does not influence the 'version' part of the package name, only its prefix:
libpmem21-1.12.1+(...).rpm
libpmem21-debuginfo-1.12.1+(...).rpm
into:
libpmem2-1.12.1+(...).rpm
libpmem2-debuginfo-1.12.1+(...).rpm
which keeps the package names consistent
( example of package names before the change )

</blockquote></details>

Thanks @tszczyp! An obscure issue it is. ;-)

**Review by janekmi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/osalyk/pmdk/10#-:-NTnbocz-Ao-6YgmC-r_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
